# Generated by Django 4.1.4 on 2023-01-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0011_profile_is_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
