# Generated by Django 4.1.4 on 2023-01-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0012_remove_profile_bio_profile_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='test',
            new_name='bio',
        ),
    ]
